### PR TITLE
Redesign and improve usability of Tic-Tac-Toe game

### PR DESCRIPTION
**Pull request by shreyadm**
Please review

Hi @Ravin972 and @Akram-Quark, I have redesigned the game as below:

image

image

I have primarily modified the HTML and CSS keeping the game logic as it is. Please let me know if this looks fine.

You can also checkout to my branch for checking the usability.
Thanks in advance!

### CODE REVIEW

**Review by ravin972 — APPROVED** [review]
# Great Job.

**Comment by shreyadm** [comment]
I have resolved the conflicts and updated the PR

**Review by ravin972 — APPROVED** [review]
reviewed

**Comment by ravin972** [comment]
Screenshot

look at this issue....

**Pull request merged**
